# Generated by Django 6.0.2 on 2026-02-19 22:51

import django.core.validators
import django.db.models.deletion
import employees.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('third_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_surname', models.CharField(max_length=100)),
                ('second_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('document_name', models.CharField(max_length=50)),
                ('document_id', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=employees.models.employee_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
                'indexes': [models.Index(fields=['employee_code'], name='idx_employee_code'), models.Index(fields=['active'], name='idx_employee_active'), models.Index(fields=['document_id'], name='idx_employee_national_id')],
            },
        ),
    ]
