# Generated by Django 6.0.2 on 2026-02-17 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='tenant/logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])]),
        ),
    ]
