# Generated by Django 6.0.2 on 2026-02-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_scope',
            field=models.CharField(choices=[('TENANT', 'Tenant User'), ('PLATFORM', 'Platform User')], default='TENANT', max_length=20),
        ),
    ]
